"""Generated by dashboard_builder.py — edit freely."""
import pandas as pd
from engine_dashboard import create_dashboard

# Load the dataframe you built this against:
df = pd.read_csv('my_dashboard.csv')

location_cols = {
    (54, 102): ['N1'],
    (54, 102): ['FNT'],
}

col_labels = {
    'N1': '[N1_Label] N1',
    'FNT': '[S2] FNT',
}

app = create_dashboard(
    image='my_dashboard_image.jpg',
    df=df,
    location_cols=location_cols,
    col_labels=col_labels,
    label_col=None,
    x_col=None,
    plot_cols=['N1', 'FNT'],
    title='my_dashboard',
    plot_layout='right',
)

if __name__ == "__main__":
    app.run(debug=True)
